/**
 * @file supplier.types.ts
 * @description Type definitions for Supplier Master module.
 */


/**
 * Supplier entity
 */
export type Supplier = {

  id: string;

  code: string;

  name: string;


  type?:
    | "Local"
    | "National"
    | "International";


  state?: string;


  address?: string;


  mobile?: string;


  whatsapp?: string;


  contact_person?: string;


  contact_person1?: string;


  contact_no1?: string;


  contact_person2?: string;


  contact_no2?: string;


  opening_balance?: number;


  status?:
    | "Active"
    | "Inactive";


  created_at?: string;


  organization_id?: string | null;

};



/**
 * Create / Update Supplier DTO
 *
 * id and created_at are generated by backend
 */
export type SupplierCreateDTO =
  Omit<
    Supplier,
    "id" | "created_at"
  >
  & {

    id?: string;

  };